### ISSUE TITLE
Worth it?

### ISSUE THREAD

**Issue by stephenplusplus** [stephenplusplus/taptapship#1]
https://github.com/stephenplusplus/taptapship/wiki/tap-tap-huh%3F

**Comment by sindresorhus** [comment]
I agree with you that stuff is currently hard and scattered, and honestly less than ideal. This is what happens in the early days of tools.

This whole thing is actually the goal of Yeoman. We tried a lot of different stuff with Yeoman and I think we've finally settled on something we really like. Yeoman is now more of a workflow/direction than just a tool.

Yeoman should provide guidance how these various recommended tools should work together in harmony.

> documentation is maintained/synced (would be nice if there was one place for updated official + user contributed docs)

We actually have that. The Yeoman docs is in the Wiki (which is editable for anyone). We've also accepted user contributed docs, and would happily accept more.

> working/not-outdated sample code, especially "get up and running" examples

That tends to happen in pre1.0 projects. Though both grunt and yeoman have docs in editable wikis. So anyone is free to fix it, or report.

> list tools that work well together

As said above. This is the goal of Yeoman. To define a great workflow of a combination of tools we feel works good together and document how you should use them.

## 

What can the Yeoman project do to help you solve these problems?

## 

Read:

https://github.com/yeoman/yeoman/wiki/The-Road-to-1.0
https://github.com/yeoman/yeoman/wiki/Migrate-from-0.9.6-to-1.0
https://github.com/yeoman/yeoman/wiki/Getting-started-with-1.0

**Comment by cowboy** [comment]
If you always want to be using the latest version of everything, yes, the tools are currently difficult to keep up with. That's because the tool authors are experimenting with new features and adjusting things based on their experiences and community feedback.

Of course, while tool authors will recommend that developers always use the latest version, developers don't have to upgrade everything, every time. They can just continue to use what they're already using until they want a new feature. At which point, well, they might have to upgrade.

I think it's just going to take a little while for things to settle down.

A word of caution: If you think that tools are nearly impossible to keep up with, imagine a developer's frustration when they go to a site like what you're proposing and _the site_ is out of date, because it hasn't been updated yet to reflect the latest changes in a tool. That might be even more frustrating.

Unless a site like what you propose is _very_ actively maintained, it could cause extra confusion.

**Comment by stephenplusplus** [comment]
Great points, @sindresorhus. This is why I, with mild resistance, asked everyone on my project at work to embrace Yeoman. It's great and extremely helpful. It is early on in the life of this and other tools (when I say tool, I mean simply "something to help me make a website"), but my point isn't to cater this to one tool over the other. My only vision for this project is giving people a place to start for understanding and help.

I would venture that the GitHub wiki was created because it made sense to keep helpful tips/documentation/future plans/change logs close to the source code. It does make sense. But even GitHub is intimidating. For starters, if you want to contribute and don't recognize Markdown, you're instantly out of the water, and back on google.

I appreciate your input. Would you say a resource like this wouldn't be of greater assistance to Yeoman users than what's available, or could we find a way to work together on planning a resource that would?

**Comment by btford** [comment]
> I think it's just going to take a little while for things to settle down.

+1

> A word of caution: If you think that tools are nearly impossible to keep up with, imagine a developer's frustration when they go to a site like what you're proposing and the site is out of date, because it hasn't been updated yet to reflect the latest changes in a tool. That might be even more frustrating.

+100

> Would you say a resource like this wouldn't be of greater assistance to Yeoman users than what's available, or could we find a way to work together on planning a resource that would?

I think you have a noble goal, but your efforts could be better spent:
1. blogging about your experiences with new tools
2. helping to improve official docs on projects you like

**Comment by stephenplusplus** [comment]
Thanks @cowboy. I can't begin to imagine all the work stacking up for you. And to reiterate--thank you!

I tagged you guys because if you can't see this working, then the reality might just be that it won't.

On the other hand, if we were to think about what it would take for this to work, would it be fair to say we would need some level of commitment from the minds behind the most notable projects?

All I mean to do is challenge where we're at now, to see if there's something that can be done better. The most important part of these tools is making sure people can use them. Imagining a world where anything is possible, the question I have is: what can we do to make it easier to use these tools?

We recognize and appreciate the difficulty of what you're doing, and all I'm challenging us to think about is if we can do it better.

Thanks again, everyone. I know you all probably have a lot of work to do, but it says a lot that you've taken the time to comment here.

**Comment by stephenplusplus** [comment]
@btford My michigangular! To break down your suggestions from the perspective of a developer:
1. (blogging) yes, I could (and do!) try to make tips and tricks I've learned available to other developers. The only problem here is, again, I have to be lucky enough to stumble upon it on google, hear about it on reddit, see a retweet from a friend, etc. I would rather know that there's one trusted resource out there, that if it can't help me directly, could at least be my starting point.
2. (improve docs) To me, this is the same as someone contributing to the docs on `taptapship`. Why have to find the project on GitHub, familiarize myself with their documentation process, and PR (in some cases) my offering of help. `taptap` would be standardized, and more welcoming for contribution.

**Comment by daspecster** [comment]
This is an interesting idea for sure.
I'm imagining something like readthedocs.org where you might have your project page but the docs are hosted on some other site that your project page links too.

I'm not sure how it would be received in the community but it might be worth an experiment.

If there was a way to use something like this to encourage people to contribute back to the projects, I think that would be really great.
For instance I went to fix a typo in the Angular docs and I had to fix my commit message styling before it was accepted. That's awesome because having commit message standards helps with managing commits on such a popular project but it might be overwhelming to a lot of people and thus discourage contributions.

I think that building on the web will become more and more difficult as the web becomes more powerful. I think a goal of any web project and developer should be to lower the barrier to entry of their project.

Web development needs to be clear and concise. I think what you're idea is leaning towards is more of what the W3C is doing in trying to standardize things. If someone took the W3C docs and just extracted the meat from them and made them easy to consume I think that would be extremely helpful!

So I think this idea has a lot of potential but it would have to be executed carefully and strategically.

Go go gadget Sawchuk!

**Comment by stephenplusplus** [comment]
@sindresorhus, @cowboy, and @btford, thanks again for your feedback. I will spend more time coming up with a concrete implementation of this currently abstract idea. If you think it's something you could get behind and your users would benefit from, it would be great to work together to help them.

**Comment by btford** [comment]
@stephenplusplus Great; I look forward to hearing more about it. To reiterate, I think the case we want to watch out for is where we have two sources of truth. I think docs should typically live in their respective projects' pages. By duplicating things across sites, you double the work of maintaining this information, and possibly confuse users if there are discrepancies. It's certainly not as glamorous, but I do think it's the best way to help on that front.

On the other hand, running an independent site for blogging/tutorials might be useful. It might be cool to say "hey, I cherry-picked these tools, and I'm going to update this site every week with posts about different aspects of using them and talk about what has changed in the tools to help users with a similar workflow stay up to date."

At very least, I wanted to commend you for your eagerness to help. Even if this particular idea doesn't pan out, there are a lot of similar efforts (like webplatform.org) that could certainly use your help. :)
